{% set name = "aiofile" %}
{% set version = "3.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiofile-{{ version }}.tar.gz
  sha256: e5ad718bb148b265b6df1b3752c4d1d83024b93da9bd599df74b9d9ffcf7919b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - caio >=0.9.0,<0.10.0
    # Conda version of ~=0.9.0
    - python >={{ python_min }}

test:
  imports:
    - aiofile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/mosquito/aiofile
  summary: Asynchronous file operations.
  license: Apache-2.0
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - BastianZim
