{% set name = "aiofile" %}
{% set version = "3.8.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiofile-{{ version }}.tar.gz
  sha256: 0eceac86711a1d610fca1d65876e8f2ef6b0a5758d6aeddd089e966b584d2052

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - caio >=0.9.0,<0.10.dev0
    # Conda version of ~=0.9.0
    - python >=3.7

test:
  imports:
    - aiofile
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/mosquito/aiofile
  summary: Asynchronous file operations.
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - BastianZim
